import Head from "next/head";
import { useRef, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const inputRef = useRef();
  const selectRef = useRef();
  const [message, setMessage] = useState(" ");
  const [urlFormat, setUrlformat] = useState(false);

  const handdleSubmit = (e) => {
    e.preventDefault();
    const url = selectRef.current.value + inputRef.current.value;
    fetch("/api/SortUrl", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ url }),
    })
      .then((res) => res.json())
      .then((data) => setMessage(` ${window.location}${data.shortUrl}`));
  };

  function isUrl() {
    var regexp = /(ftp|http|https):\/\/[\w\-]+(\.[\w\-]+)+[/#?]?.*$/;
    const match = regexp.test(selectRef.current.value + inputRef.current.value);
    setUrlformat(match);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>SHORTurURL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/tijeras.svg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>SHORT ur URL</h1>

        <p className={styles.description}>short your URL</p>

        <div className={styles.grid}>
          <form className="" onSubmit={handdleSubmit} onChange={isUrl}>
            <select name="protocol" ref={selectRef} defaultValue="http://">
              <option value="http://">Http://</option>
              <option value="https://">Https://</option>
            </select>
            <input
              spellCheck={false}
              ref={inputRef}
              type="text"
              placeholder="URL to short"
            />
            <button disabled={!urlFormat}>Short</button>
            <div className={styles.resultUrl}>
              <b>Short URL: </b>
              {message}
            </div>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Kasita.es<span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
}
